# doc2vec with gensim

This notebook demonstrates the basic commands needed to train a doc2vec model using the functions provided by gensim by working through a toy example. Here python 2.7 and gensim version 2.2.0 are used.

doc2vec is an extension of word2vec which converts documents (these could be any sequences of words – paragraphs, comments, or even whole documents). This notebook only demonstrates how to use the technique; it does not explain how it works. For details consult the paper by Le and Mikolov: https://arxiv.org/abs/1405.4053.

## Documents to vectors
In this first section we will show how to produce a vector for each document. First load the required packages.

In [1]:
import re
import numpy as np
import pandas as pd

from gensim.models.doc2vec import TaggedDocument
from gensim.models.doc2vec import Doc2Vec

### Define helper functions
Next we need to define a couple of helper functions. One which splits ('tokenises') a string into a list of words, and one which takes puts our data into the data structure gensim is expecting.

In [2]:
# Tokenise on whitespace
def tokeniser(text):
    return re.findall(r"\S+", text)

# Create labelled sentence data structure
def labeller_id(ID, text):
    return TaggedDocument(tokeniser(text), [ID])

Let's see what the tokeniser does:

In [3]:
tokeniser('an example string of text')

['an', 'example', 'string', 'of', 'text']

This is a very simple tokeniser, much more advanced ones are available. 

Doc2vec expects data in the 'TaggedDocument' format, which is a list of words within the documents and a list of IDs. In this case we are creating one vector per document so each document needs one, unique ID. For example:

In [4]:
ex_document = 'an example document'
ex_id = 'doc1'
labeller_id(ex_id, ex_document)

TaggedDocument(words=['an', 'example', 'document'], tags=['doc1'])

### Getting data into the right format
Let's consider the example where we have text within a pandas dataframe.

In [5]:
# Create example data
df = pd.DataFrame()
df['text'] = [
                'this is text', 
                'any more text?', 
                'even more text!', 
                'words, all words'
            ]

We can use the dataframe IDs as the document IDs and convert all the documents into the required TaggedDocument format. If there is a column with unique IDs, this column could be used instead.

In [6]:
# Get data into correct format
documents =  df.apply(lambda x: labeller_id(x.name, x['text']), axis=1).values
documents

array([TaggedDocument(words=['this', 'is', 'text'], tags=[0]),
       TaggedDocument(words=['any', 'more', 'text?'], tags=[1]),
       TaggedDocument(words=['even', 'more', 'text!'], tags=[2]),
       TaggedDocument(words=['words,', 'all', 'words'], tags=[3])], dtype=object)

### Build the model
Now we can build the doc2vec model and then delete some of the items created by gensim during the model build in order to free up memory.

In [7]:
# Build model
model = Doc2Vec(documents = documents,
        size = 5,
        seed = 40,
        min_count = 0,
        max_vocab_size = None,
        window =2,
        iter = 5)

# Free up memory
model.delete_temporary_training_data(keep_doctags_vectors=True, keep_inference=True)

We can retrieve the vectors produced for each of the documents

In [8]:
model.docvecs.doctag_syn0

array([[-0.00165228],
       [ 0.28662241],
       [ 0.3524237 ],
       [ 0.39406374]], dtype=float32)

or we can retrieve documents by specifying the ID.

In [9]:
model.docvecs[1]

array([ 0.28662241], dtype=float32)

If strings had been used for IDs the command model.docvecs.doctags.keys() could be used to retrieve these strings, but this command does not necessarily return them in the same order as doctag_syn0.

### Using the model
Vectors for new documents can be inferred:

In [10]:
new_sentence = ['one', 'more', 'sentence']
model.infer_vector(new_sentence)

array([-0.49406224], dtype=float32)

As can the vectors for multiple sentences:

In [11]:
new_sentences = [ ['first', 'text'], ['second', 'test']]
np.matrix(map(model.infer_vector, new_sentences))

matrix([[ 0.15742688],
        [ 0.02989352]], dtype=float32)

You can also get the most similiar documents to a new document:

In [12]:
new_text = "any old text"
new_vector = model.infer_vector(tokeniser(new_text))
similar = model.docvecs.most_similar([new_vector], topn=1)

# Print the closest tag and the similarity score
print similar

# Print the text
df.loc[similar[0][0], 'text']

[(1, 1.0)]


'any more text?'

### Caution: inferring vectors for training documents

When given a document used to train the model the infer_vectors function is not guaranteed to return the same vector as that associated with the document in the model itself. For example,

In [13]:
print "Model vector for document 0:"
print model.docvecs[0]
print "Inferred vector for document 0:"
print model.infer_vector( tokeniser(df.loc[0,'text']))

Model vector for document 0:
[-0.00165228]
Inferred vector for document 0:
[-0.35209045]


It is safer to explictly retrieve the vectors for documents that were used to train the model. Modelling tuning should help to reduce this discrepancy.

## Topics to vectors

Another way in which doc2vec can be used is to learn vectors for topics rather than for individual documents. To do this instead of giving the model a unique ID for each document you instead pass a list of topics. Each document can have multiple topics.

Let's demonstrate. First we need to tweak our labeller function so that it takes a list as input rather than a single ID. This reuses the tokeniser function defined previously

In [14]:
# Create labelled sentence data structure when given topic list
def labeller_topics(topic_list, text):
    return TaggedDocument(tokeniser(text), topic_list)

Next define some example data where there are two topics: 'question' and 'cats'.

In [15]:
# Create example data
df2 = pd.DataFrame()
df2['text'] = [
    'is there any more text?',
    'where are the words of the documents',
    'cats like to chase mice',
    'cats do not like dogs',
    'do you like cats?'
    ]

# Each document can have multiple topics associated with it (list of topics per document)
df2['topic'] = [
    ['question'],
    ['question'],
    ['cats'],
    ['cats'],
    ['question', 'cats']
    ]

df2

text             topic
0               is there any more text?        [question]
1  where are the words of the documents        [question]
2               cats like to chase mice            [cats]
3                 cats do not like dogs            [cats]
4                     do you like cats?  [question, cats]

This can be converted into TaggedDocument form using the new labeller_topics function.

In [16]:
documents2 = df2.apply(lambda x: labeller_topics(x['topic'], x['text']), axis=1).values

Then a doc2vec model can be build as before.

In [17]:
# Build model
model2 = Doc2Vec(documents = documents2,
        size = 2,
        seed = 42,
        min_count = 1,
        max_vocab_size = None,
        window = 5,
        iter = 5)

# Free up memory
model2.delete_temporary_training_data(keep_doctags_vectors=True, keep_inference=True)

Let's look at the document vectors:

In [18]:
model2.docvecs.doctag_syn0

array([[-0.03462205, -0.05810256],
       [ 0.10018398,  0.24293993]], dtype=float32)

and note only two vectors have been produced. This is encouraging as we only had two topics. Checking the tags of these vectors gives the two topics we were expecting.

In [19]:
model2.docvecs.doctags.keys()

['cats', 'question']

Note, the command above returns all the topics but the order does not necessarily correspond to the order of the vectors in doctag_syn0. For example, the command above returns 'cats' as the first topic but if we look at the 'cats' vector

In [20]:
model2.docvecs['cats']

array([ 0.10018398,  0.24293993], dtype=float32)

we see it is the second vector in the doctag_syn0 array not the first. The safest way to retrieve a list of topics and their vectors in the correct order is to explictly retrieve them by name. For example, if we wanted a dataframe containing topics and their vectors we could do the following.

In [21]:
df_topics = pd.DataFrame()

# Store the topics
df_topics['topics'] = model2.docvecs.doctags.keys()

# Explictly retrieve the vectors
df_topics['vectors'] = df_topics['topics'].apply(lambda x: model2.docvecs[x])
df_topics

topics                  vectors
0      cats      [0.100184, 0.24294]
1  question  [-0.034622, -0.0581026]